# This is the configuration used to check the rubocop source code.

AllCops:
  Exclude:
    - spec/support/spec_helper.rb
    - spec/rails_helper.rb

Documentation:
  Enabled: false

LineLength:
  Max: 99

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
