# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_bucket_name: <%= ENV['AWS_BUCKET_NAME'] %>
  aws_region: <%= ENV['AWS_REGION'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  email_recipients_interceptors: <%= ENV['EMAIL_RECIPIENTS_INTERCEPTOR'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  domain_secret: <%= ENV['DOMAIN_MAILGUN'] %>
  user_name_secret: <%= ENV['USER_NAME_MAILGUN'] %>
  password_secret: <%= ENV['PASSWORD_MAILGUN'] %>

development: &development
  <<: *default
  secret_key_base: e369575030a3ac3c396ccb152187c43e61e03721a910e5a90a1153c0f06b04c2a2b750ffb0020152a6580c261cb86ae11936f0ea2deec6380012b33d35b7fd3c

test:
  <<: *default
  secret_key_base: 8bb1853c2c5627b92dbd0a40cdf3eecd9c443766d8e5a006fbd2e65a7b40e19a8c926db2e85af279c5db36576e7e38f3a047e4cd24249926760323ec9cb8127d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
