:concurrency: 1
:queues:
  - default
  - mailers

:schedule:
  notify_when_rent_over_worker:
    every: 24h
    class: NotifyWhenRentOverWorker

  notify_when_rent_almost_over_worker:
    every: 24h
    class: NotifyWhenRentAlmostOverWorker
